name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Load cached dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          .venv
          poetry.lock
        key: poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Install package
      run: poetry install --no-interaction

    - name: Build package
      run: poetry build

    - name: Publish to PyPI
      run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}